import { Londrina_Solid } from "next/font/google";
import "./globals.css";

const londrina = Londrina_Solid({ subsets: ["latin"], variable: '--font-londrina',
	  weight: "400", display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={londrina.className}>{children}</body>
    </html>
  );
}
